### ISSUE TITLE
Destroying statuses can leave requests without a status

### ISSUE THREAD

**Issue by jmacdonald** [jmacdonald/triage#1]
We might need to set affected requests to the default status.

**Comment by cschiewek** [comment]
Options: 
- Allow requests without statuses
- Have a "default status" that can't be deleted, and requests would revert to that status if their current status is deleted
- Prevent statuses from being deleted if they are associated to a request (my preference)

**Comment by jmacdonald** [comment]
I'm on board with the last item as well. Seems like a simple `before_destroy` callback, with associated unit tests. You can run with this, if interested.
