### ISSUE TITLE
Re-route users after login based on role

### ISSUE THREAD

**Issue by jmacdonald** [jmacdonald/triage#14]
The default root path goes to "All Requests", which is really only suitable for admins. This should be based on the user role, routing to "My Assignments" for providers and "My Requests" for requesters.

**Comment by cschiewek** [comment]
Seems to me we could do this all in the routes file using constraints.  Define 3 root routes and constrain them based on role.

**Comment by jmacdonald** [comment]
Pull request? :)

**Comment by cschiewek** [comment]
I'm working on it now.  Way cleaner then redirecting from a controller action.
